# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: BOAT Program
author: BOAT Team, University of Washington
# logo: logo.png
only_build_toc_files: true

parse:
  # https://jupyterbook.org/content/content-blocks.html?highlight=myst%20substitution#define-substitutions-for-your-whole-book
  # https://jupyterbook.org/content/content-blocks.html#using-substitutions-in-links
  myst_substitutions:
    hackweek: "BOAT"
    dates: "October ? to ?, 2021"  # TODO: REMOVE
    github_org_url: "https://github.com/BOAT-ocean-acoustics"
    book_repo: "boat-website"
    website_url: "https://boat-ocean-acoustics.github.io"
    jupyterhub_url: "https://INSERT_JUPYTERHUB_URL"  # TODO: CHANGE
    slack_workspace_url: "https://INSERT_SLACK_URL"  # TODO: CHANGE
    contact_email: "boat.ocean.acoustics@gmail.com"
    dataset: "INSERT_DATA_SET_NAME"  # TODO: REMOVE
    anon_reporting_url: "https://INSERT_FORM_LINK"  # TODO: CHANGE
    project_spreadsheet_url: "https://INSERT_GOOGLE_SHEET"  # TODO: REMOVE
  myst_enable_extensions:
    # Defaults
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    # Extras
    - html_image

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  # NOTE: 'cache' to use jupyter-cache, or 'force' to run all
  execute_notebooks: 'force'
  exclude_patterns:
    - "**/geospatial-advanced.ipynb"
  allow_errors: false
  # Per-cell notebook execution limit (seconds)
  timeout: 300

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: "https://mybinder.org"

# Information about where the book exists on the web
repository:
  url: https://github.com/BOAT-ocean-acoustics/boat-ocean-acoustics.github.io # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Bibliography
bibtex_bibfiles:
  - references.bib
sphinx:
  recursive_update: true  # needed to default to light mode
  config:
    bibtex_reference_style: author_year  # or label, super, \supercite
    nb_merge_streams: true # stdout lines combined in output
    nb_custom_formats:
        .py:
            - jupytext.reads
            - fmt: py:percent
    suppress_warnings: [myst.header]
    # Default to light mode
    # See: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/light-dark.html#configure-default-theme-mode
    html_context:
      default_mode: light
    html_theme_options:
      navbar_end: [navbar-icon-links]  # somehow this does not work



# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  # google_analytics_id: G-XXXXXXXXX
